In [1]:
import torch
import dgl
%load_ext autoreload
%autoreload 2
import hpno as hq

Using backend: pytorch


In [76]:
ds = hq.data.lipophilicity()
ds_tr, ds_te = hq.data.utils.split(ds, [4, 1])
ds_tr = hq.data.utils.batch(ds_tr, 32)
ds_te = hq.data.utils.batch(ds_te, len(ds_te))

In [39]:
# pinot
import pinot
ds = pinot.data.lipophilicity()
ds_tr, ds_te = pinot.data.utils.split(ds, [4, 1])
ds_tr = pinot.data.utils.batch(ds_tr, 32)
ds_te = pinot.data.utils.batch(ds_te, len(ds_te))

In [38]:
ds = hq.data.lipophilicity()
ds_tr, ds_te = hq.data.utils.split(ds, [4, 1])
ds_te = hq.data.utils.batch(ds_te, len(ds_te))

/Users/wangy1/anaconda3/envs/pinot/lib/python3.7/site-packages/dgl/base.py:25: UserWarning: Currently adjacency_matrix() returns a matrix with destination as rows by default.  In 0.5 the result will have source as rows (i.e. transpose=True)
  warnings.warn(msg, warn_type)


KeyboardInterrupt: 

In [46]:
net = torch.nn.Sequential(
    hq.models.input_layer.InputLayer(),
    hq.models.hmp.HierarchicalMessagePassing(),
    hq.models.output_layer.MultiPool(),
)

In [47]:
# pinot
net = pinot.Net(
    pinot.representation.Sequential(
        pinot.representation.dgl_legacy.gn(),
        [32, 'tanh', 32, 'tanh', 32, 'tanh']),
    output_regressor=pinot.regressors.ExactGaussianProcessRegressor)

In [48]:
optimizer = torch.optim.Adam(net.parameters(), 1e-3)

In [49]:
loss_fn = torch.nn.functional.mse_loss

In [50]:
for _ in range(100):
    for g, y in ds_tr:
        optimizer.zero_grad()
        loss = net.loss(g, y)
        loss.backward()
        print(loss)
        optimizer.step()

tensor([[131.6746]], grad_fn=<AddBackward0>)
tensor([[120.8255]], grad_fn=<AddBackward0>)
tensor([[124.0382]], grad_fn=<AddBackward0>)
tensor([[98.9233]], grad_fn=<AddBackward0>)
tensor([[124.4608]], grad_fn=<AddBackward0>)
tensor([[107.6901]], grad_fn=<AddBackward0>)
tensor([[114.4276]], grad_fn=<AddBackward0>)
tensor([[122.6411]], grad_fn=<AddBackward0>)
tensor([[100.1456]], grad_fn=<AddBackward0>)
tensor([[104.2112]], grad_fn=<AddBackward0>)
tensor([[128.1805]], grad_fn=<AddBackward0>)
tensor([[104.9752]], grad_fn=<AddBackward0>)
tensor([[108.3207]], grad_fn=<AddBackward0>)
tensor([[107.9654]], grad_fn=<AddBackward0>)
tensor([[92.4029]], grad_fn=<AddBackward0>)
tensor([[105.5506]], grad_fn=<AddBackward0>)
tensor([[101.8091]], grad_fn=<AddBackward0>)
tensor([[101.6830]], grad_fn=<AddBackward0>)
tensor([[101.0815]], grad_fn=<AddBackward0>)
tensor([[108.0400]], grad_fn=<AddBackward0>)
tensor([[109.1160]], grad_fn=<AddBackward0>)
tensor([[114.2736]], grad_fn=<AddBackward0>)
tensor([[94.

tensor([[109.7888]], grad_fn=<AddBackward0>)
tensor([[96.1993]], grad_fn=<AddBackward0>)
tensor([[81.8678]], grad_fn=<AddBackward0>)
tensor([[92.7496]], grad_fn=<AddBackward0>)
tensor([[96.0890]], grad_fn=<AddBackward0>)
tensor([[99.8262]], grad_fn=<AddBackward0>)
tensor([[88.2663]], grad_fn=<AddBackward0>)
tensor([[113.7085]], grad_fn=<AddBackward0>)
tensor([[92.2334]], grad_fn=<AddBackward0>)
tensor([[92.6008]], grad_fn=<AddBackward0>)
tensor([[87.7093]], grad_fn=<AddBackward0>)
tensor([[90.1041]], grad_fn=<AddBackward0>)
tensor([[83.1983]], grad_fn=<AddBackward0>)
tensor([[93.2242]], grad_fn=<AddBackward0>)
tensor([[83.3632]], grad_fn=<AddBackward0>)
tensor([[101.6760]], grad_fn=<AddBackward0>)
tensor([[104.3238]], grad_fn=<AddBackward0>)
tensor([[100.1141]], grad_fn=<AddBackward0>)
tensor([[91.0880]], grad_fn=<AddBackward0>)
tensor([[111.7457]], grad_fn=<AddBackward0>)
tensor([[92.8150]], grad_fn=<AddBackward0>)
tensor([[102.7257]], grad_fn=<AddBackward0>)
tensor([[100.9591]], grad

tensor([[90.9716]], grad_fn=<AddBackward0>)
tensor([[91.8371]], grad_fn=<AddBackward0>)
tensor([[88.6699]], grad_fn=<AddBackward0>)
tensor([[84.4812]], grad_fn=<AddBackward0>)
tensor([[93.9913]], grad_fn=<AddBackward0>)
tensor([[90.1680]], grad_fn=<AddBackward0>)
tensor([[82.6975]], grad_fn=<AddBackward0>)
tensor([[83.8542]], grad_fn=<AddBackward0>)
tensor([[83.2682]], grad_fn=<AddBackward0>)
tensor([[94.9208]], grad_fn=<AddBackward0>)
tensor([[102.0867]], grad_fn=<AddBackward0>)
tensor([[104.1413]], grad_fn=<AddBackward0>)
tensor([[93.3069]], grad_fn=<AddBackward0>)
tensor([[80.4946]], grad_fn=<AddBackward0>)
tensor([[90.5346]], grad_fn=<AddBackward0>)
tensor([[92.3908]], grad_fn=<AddBackward0>)
tensor([[96.2239]], grad_fn=<AddBackward0>)
tensor([[86.7621]], grad_fn=<AddBackward0>)
tensor([[105.9408]], grad_fn=<AddBackward0>)
tensor([[88.1338]], grad_fn=<AddBackward0>)
tensor([[87.6046]], grad_fn=<AddBackward0>)
tensor([[85.5549]], grad_fn=<AddBackward0>)
tensor([[85.9765]], grad_fn=<

tensor([[86.2985]], grad_fn=<AddBackward0>)
tensor([[84.2873]], grad_fn=<AddBackward0>)
tensor([[86.3906]], grad_fn=<AddBackward0>)
tensor([[84.4177]], grad_fn=<AddBackward0>)
tensor([[81.0280]], grad_fn=<AddBackward0>)
tensor([[86.8054]], grad_fn=<AddBackward0>)
tensor([[93.6394]], grad_fn=<AddBackward0>)
tensor([[84.8271]], grad_fn=<AddBackward0>)
tensor([[93.6208]], grad_fn=<AddBackward0>)
tensor([[84.2729]], grad_fn=<AddBackward0>)
tensor([[77.7571]], grad_fn=<AddBackward0>)
tensor([[81.1817]], grad_fn=<AddBackward0>)
tensor([[87.8206]], grad_fn=<AddBackward0>)
tensor([[82.1709]], grad_fn=<AddBackward0>)
tensor([[89.1297]], grad_fn=<AddBackward0>)
tensor([[88.2887]], grad_fn=<AddBackward0>)
tensor([[88.6806]], grad_fn=<AddBackward0>)
tensor([[85.5888]], grad_fn=<AddBackward0>)
tensor([[83.4381]], grad_fn=<AddBackward0>)
tensor([[94.2022]], grad_fn=<AddBackward0>)
tensor([[87.7719]], grad_fn=<AddBackward0>)
tensor([[82.2837]], grad_fn=<AddBackward0>)
tensor([[83.1871]], grad_fn=<Add

tensor([[93.3958]], grad_fn=<AddBackward0>)
tensor([[87.4593]], grad_fn=<AddBackward0>)
tensor([[90.3181]], grad_fn=<AddBackward0>)
tensor([[100.3620]], grad_fn=<AddBackward0>)
tensor([[88.1343]], grad_fn=<AddBackward0>)
tensor([[82.2062]], grad_fn=<AddBackward0>)
tensor([[84.2589]], grad_fn=<AddBackward0>)
tensor([[89.5322]], grad_fn=<AddBackward0>)
tensor([[88.1067]], grad_fn=<AddBackward0>)
tensor([[92.4485]], grad_fn=<AddBackward0>)
tensor([[99.8488]], grad_fn=<AddBackward0>)
tensor([[94.6608]], grad_fn=<AddBackward0>)
tensor([[92.5074]], grad_fn=<AddBackward0>)
tensor([[86.5895]], grad_fn=<AddBackward0>)
tensor([[79.9345]], grad_fn=<AddBackward0>)
tensor([[84.9881]], grad_fn=<AddBackward0>)
tensor([[90.9482]], grad_fn=<AddBackward0>)
tensor([[86.8086]], grad_fn=<AddBackward0>)
tensor([[80.4661]], grad_fn=<AddBackward0>)
tensor([[84.7880]], grad_fn=<AddBackward0>)
tensor([[86.0873]], grad_fn=<AddBackward0>)
tensor([[83.4762]], grad_fn=<AddBackward0>)
tensor([[87.3882]], grad_fn=<Ad

tensor([[89.0763]], grad_fn=<AddBackward0>)
tensor([[89.8447]], grad_fn=<AddBackward0>)
tensor([[82.9480]], grad_fn=<AddBackward0>)
tensor([[82.8877]], grad_fn=<AddBackward0>)
tensor([[90.5651]], grad_fn=<AddBackward0>)
tensor([[94.6712]], grad_fn=<AddBackward0>)
tensor([[88.3662]], grad_fn=<AddBackward0>)
tensor([[95.4416]], grad_fn=<AddBackward0>)
tensor([[86.0909]], grad_fn=<AddBackward0>)
tensor([[93.4527]], grad_fn=<AddBackward0>)
tensor([[85.2998]], grad_fn=<AddBackward0>)
tensor([[87.3331]], grad_fn=<AddBackward0>)
tensor([[100.6015]], grad_fn=<AddBackward0>)
tensor([[85.2106]], grad_fn=<AddBackward0>)
tensor([[81.2987]], grad_fn=<AddBackward0>)
tensor([[81.8583]], grad_fn=<AddBackward0>)
tensor([[87.7203]], grad_fn=<AddBackward0>)
tensor([[88.8660]], grad_fn=<AddBackward0>)
tensor([[92.7025]], grad_fn=<AddBackward0>)
tensor([[98.2724]], grad_fn=<AddBackward0>)
tensor([[92.7613]], grad_fn=<AddBackward0>)
tensor([[91.6932]], grad_fn=<AddBackward0>)
tensor([[85.3282]], grad_fn=<Ad

tensor([[86.8965]], grad_fn=<AddBackward0>)
tensor([[93.5412]], grad_fn=<AddBackward0>)
tensor([[84.0083]], grad_fn=<AddBackward0>)
tensor([[90.8204]], grad_fn=<AddBackward0>)
tensor([[76.4806]], grad_fn=<AddBackward0>)
tensor([[92.5095]], grad_fn=<AddBackward0>)
tensor([[84.3319]], grad_fn=<AddBackward0>)
tensor([[81.4818]], grad_fn=<AddBackward0>)
tensor([[80.8917]], grad_fn=<AddBackward0>)
tensor([[83.7650]], grad_fn=<AddBackward0>)
tensor([[87.2281]], grad_fn=<AddBackward0>)
tensor([[88.3469]], grad_fn=<AddBackward0>)
tensor([[88.5339]], grad_fn=<AddBackward0>)
tensor([[85.8568]], grad_fn=<AddBackward0>)
tensor([[88.0287]], grad_fn=<AddBackward0>)
tensor([[82.9300]], grad_fn=<AddBackward0>)
tensor([[89.3105]], grad_fn=<AddBackward0>)
tensor([[86.1217]], grad_fn=<AddBackward0>)
tensor([[85.4265]], grad_fn=<AddBackward0>)
tensor([[88.0954]], grad_fn=<AddBackward0>)
tensor([[87.7719]], grad_fn=<AddBackward0>)
tensor([[88.6369]], grad_fn=<AddBackward0>)
tensor([[89.6839]], grad_fn=<Add

tensor([[86.8370]], grad_fn=<AddBackward0>)
tensor([[79.7657]], grad_fn=<AddBackward0>)
tensor([[84.2487]], grad_fn=<AddBackward0>)
tensor([[90.1782]], grad_fn=<AddBackward0>)
tensor([[93.2406]], grad_fn=<AddBackward0>)
tensor([[80.8275]], grad_fn=<AddBackward0>)
tensor([[102.2784]], grad_fn=<AddBackward0>)
tensor([[85.9388]], grad_fn=<AddBackward0>)
tensor([[89.1314]], grad_fn=<AddBackward0>)
tensor([[83.9311]], grad_fn=<AddBackward0>)
tensor([[83.7295]], grad_fn=<AddBackward0>)
tensor([[87.2307]], grad_fn=<AddBackward0>)
tensor([[86.6661]], grad_fn=<AddBackward0>)
tensor([[82.4246]], grad_fn=<AddBackward0>)
tensor([[91.9597]], grad_fn=<AddBackward0>)
tensor([[82.8318]], grad_fn=<AddBackward0>)
tensor([[83.2200]], grad_fn=<AddBackward0>)
tensor([[91.7844]], grad_fn=<AddBackward0>)
tensor([[82.4494]], grad_fn=<AddBackward0>)
tensor([[88.0515]], grad_fn=<AddBackward0>)
tensor([[76.8416]], grad_fn=<AddBackward0>)
tensor([[88.3398]], grad_fn=<AddBackward0>)
tensor([[85.3042]], grad_fn=<Ad

tensor([[82.7914]], grad_fn=<AddBackward0>)
tensor([[86.5324]], grad_fn=<AddBackward0>)
tensor([[89.6211]], grad_fn=<AddBackward0>)
tensor([[80.3837]], grad_fn=<AddBackward0>)
tensor([[85.8850]], grad_fn=<AddBackward0>)
tensor([[81.5188]], grad_fn=<AddBackward0>)
tensor([[81.8182]], grad_fn=<AddBackward0>)
tensor([[80.6062]], grad_fn=<AddBackward0>)
tensor([[81.4413]], grad_fn=<AddBackward0>)
tensor([[76.9426]], grad_fn=<AddBackward0>)
tensor([[83.7478]], grad_fn=<AddBackward0>)
tensor([[78.7341]], grad_fn=<AddBackward0>)
tensor([[83.4732]], grad_fn=<AddBackward0>)
tensor([[91.3292]], grad_fn=<AddBackward0>)
tensor([[90.3381]], grad_fn=<AddBackward0>)
tensor([[80.9684]], grad_fn=<AddBackward0>)
tensor([[94.8560]], grad_fn=<AddBackward0>)
tensor([[83.8693]], grad_fn=<AddBackward0>)
tensor([[86.1383]], grad_fn=<AddBackward0>)
tensor([[82.0020]], grad_fn=<AddBackward0>)
tensor([[81.3944]], grad_fn=<AddBackward0>)
tensor([[86.4846]], grad_fn=<AddBackward0>)
tensor([[84.7776]], grad_fn=<Add

tensor([[87.1561]], grad_fn=<AddBackward0>)
tensor([[79.3763]], grad_fn=<AddBackward0>)
tensor([[76.4704]], grad_fn=<AddBackward0>)
tensor([[78.4282]], grad_fn=<AddBackward0>)
tensor([[83.2890]], grad_fn=<AddBackward0>)
tensor([[80.1259]], grad_fn=<AddBackward0>)
tensor([[86.0440]], grad_fn=<AddBackward0>)
tensor([[80.4902]], grad_fn=<AddBackward0>)
tensor([[79.1289]], grad_fn=<AddBackward0>)
tensor([[82.3184]], grad_fn=<AddBackward0>)
tensor([[80.2638]], grad_fn=<AddBackward0>)
tensor([[84.4281]], grad_fn=<AddBackward0>)
tensor([[80.8686]], grad_fn=<AddBackward0>)
tensor([[82.5698]], grad_fn=<AddBackward0>)
tensor([[81.0865]], grad_fn=<AddBackward0>)
tensor([[80.6239]], grad_fn=<AddBackward0>)
tensor([[86.0119]], grad_fn=<AddBackward0>)
tensor([[89.1041]], grad_fn=<AddBackward0>)
tensor([[98.9994]], grad_fn=<AddBackward0>)
tensor([[88.1080]], grad_fn=<AddBackward0>)
tensor([[79.8792]], grad_fn=<AddBackward0>)
tensor([[84.2856]], grad_fn=<AddBackward0>)
tensor([[88.4811]], grad_fn=<Add

tensor([[84.2716]], grad_fn=<AddBackward0>)
tensor([[82.3814]], grad_fn=<AddBackward0>)
tensor([[81.2715]], grad_fn=<AddBackward0>)
tensor([[81.2485]], grad_fn=<AddBackward0>)
tensor([[77.7539]], grad_fn=<AddBackward0>)
tensor([[85.8315]], grad_fn=<AddBackward0>)
tensor([[85.8992]], grad_fn=<AddBackward0>)
tensor([[83.3339]], grad_fn=<AddBackward0>)
tensor([[87.2813]], grad_fn=<AddBackward0>)
tensor([[79.8924]], grad_fn=<AddBackward0>)
tensor([[78.2653]], grad_fn=<AddBackward0>)
tensor([[79.3138]], grad_fn=<AddBackward0>)
tensor([[84.9904]], grad_fn=<AddBackward0>)
tensor([[79.1118]], grad_fn=<AddBackward0>)
tensor([[87.3560]], grad_fn=<AddBackward0>)
tensor([[81.8318]], grad_fn=<AddBackward0>)
tensor([[82.5591]], grad_fn=<AddBackward0>)
tensor([[85.8285]], grad_fn=<AddBackward0>)
tensor([[82.4137]], grad_fn=<AddBackward0>)
tensor([[83.9817]], grad_fn=<AddBackward0>)
tensor([[82.5892]], grad_fn=<AddBackward0>)
tensor([[83.9930]], grad_fn=<AddBackward0>)
tensor([[80.9990]], grad_fn=<Add

tensor([[84.2728]], grad_fn=<AddBackward0>)
tensor([[87.9422]], grad_fn=<AddBackward0>)
tensor([[90.0345]], grad_fn=<AddBackward0>)
tensor([[94.0946]], grad_fn=<AddBackward0>)
tensor([[84.0982]], grad_fn=<AddBackward0>)
tensor([[90.2444]], grad_fn=<AddBackward0>)
tensor([[85.7797]], grad_fn=<AddBackward0>)
tensor([[81.1988]], grad_fn=<AddBackward0>)
tensor([[80.9146]], grad_fn=<AddBackward0>)
tensor([[89.5656]], grad_fn=<AddBackward0>)
tensor([[81.9884]], grad_fn=<AddBackward0>)
tensor([[77.8642]], grad_fn=<AddBackward0>)
tensor([[79.6913]], grad_fn=<AddBackward0>)
tensor([[82.8029]], grad_fn=<AddBackward0>)
tensor([[82.7999]], grad_fn=<AddBackward0>)
tensor([[80.0490]], grad_fn=<AddBackward0>)
tensor([[80.7426]], grad_fn=<AddBackward0>)
tensor([[76.9564]], grad_fn=<AddBackward0>)
tensor([[86.3032]], grad_fn=<AddBackward0>)
tensor([[84.2886]], grad_fn=<AddBackward0>)
tensor([[81.5040]], grad_fn=<AddBackward0>)
tensor([[86.9163]], grad_fn=<AddBackward0>)
tensor([[77.8124]], grad_fn=<Add

tensor([[78.8062]], grad_fn=<AddBackward0>)
tensor([[82.1277]], grad_fn=<AddBackward0>)
tensor([[84.3091]], grad_fn=<AddBackward0>)
tensor([[84.7941]], grad_fn=<AddBackward0>)
tensor([[86.5524]], grad_fn=<AddBackward0>)
tensor([[91.0747]], grad_fn=<AddBackward0>)
tensor([[84.9540]], grad_fn=<AddBackward0>)
tensor([[85.6591]], grad_fn=<AddBackward0>)
tensor([[83.3366]], grad_fn=<AddBackward0>)
tensor([[80.4241]], grad_fn=<AddBackward0>)
tensor([[94.7205]], grad_fn=<AddBackward0>)
tensor([[81.4183]], grad_fn=<AddBackward0>)
tensor([[81.3820]], grad_fn=<AddBackward0>)
tensor([[79.0019]], grad_fn=<AddBackward0>)
tensor([[83.8528]], grad_fn=<AddBackward0>)
tensor([[85.7656]], grad_fn=<AddBackward0>)
tensor([[90.3509]], grad_fn=<AddBackward0>)
tensor([[95.2636]], grad_fn=<AddBackward0>)
tensor([[84.2613]], grad_fn=<AddBackward0>)
tensor([[88.3860]], grad_fn=<AddBackward0>)
tensor([[85.8114]], grad_fn=<AddBackward0>)
tensor([[82.0679]], grad_fn=<AddBackward0>)
tensor([[80.7170]], grad_fn=<Add

tensor([[86.3617]], grad_fn=<AddBackward0>)
tensor([[82.3469]], grad_fn=<AddBackward0>)
tensor([[81.9109]], grad_fn=<AddBackward0>)
tensor([[88.6587]], grad_fn=<AddBackward0>)
tensor([[86.2885]], grad_fn=<AddBackward0>)
tensor([[86.3691]], grad_fn=<AddBackward0>)
tensor([[85.8553]], grad_fn=<AddBackward0>)
tensor([[83.3795]], grad_fn=<AddBackward0>)
tensor([[81.5831]], grad_fn=<AddBackward0>)
tensor([[87.8383]], grad_fn=<AddBackward0>)
tensor([[87.7086]], grad_fn=<AddBackward0>)
tensor([[85.9642]], grad_fn=<AddBackward0>)
tensor([[91.3032]], grad_fn=<AddBackward0>)
tensor([[85.5621]], grad_fn=<AddBackward0>)
tensor([[82.8030]], grad_fn=<AddBackward0>)
tensor([[83.3214]], grad_fn=<AddBackward0>)
tensor([[78.5058]], grad_fn=<AddBackward0>)
tensor([[94.0173]], grad_fn=<AddBackward0>)
tensor([[82.3900]], grad_fn=<AddBackward0>)
tensor([[80.2055]], grad_fn=<AddBackward0>)
tensor([[80.3424]], grad_fn=<AddBackward0>)
tensor([[85.7058]], grad_fn=<AddBackward0>)
tensor([[88.0465]], grad_fn=<Add

tensor([[79.9242]], grad_fn=<AddBackward0>)
tensor([[87.7120]], grad_fn=<AddBackward0>)
tensor([[83.4637]], grad_fn=<AddBackward0>)
tensor([[78.8929]], grad_fn=<AddBackward0>)
tensor([[89.3988]], grad_fn=<AddBackward0>)
tensor([[81.5993]], grad_fn=<AddBackward0>)
tensor([[86.2319]], grad_fn=<AddBackward0>)
tensor([[76.2260]], grad_fn=<AddBackward0>)
tensor([[84.2481]], grad_fn=<AddBackward0>)
tensor([[80.8875]], grad_fn=<AddBackward0>)
tensor([[79.3801]], grad_fn=<AddBackward0>)
tensor([[81.7622]], grad_fn=<AddBackward0>)
tensor([[82.0947]], grad_fn=<AddBackward0>)
tensor([[84.9593]], grad_fn=<AddBackward0>)
tensor([[83.6992]], grad_fn=<AddBackward0>)
tensor([[85.0575]], grad_fn=<AddBackward0>)
tensor([[81.8610]], grad_fn=<AddBackward0>)
tensor([[80.9165]], grad_fn=<AddBackward0>)
tensor([[79.5673]], grad_fn=<AddBackward0>)
tensor([[87.8788]], grad_fn=<AddBackward0>)
tensor([[83.1851]], grad_fn=<AddBackward0>)
tensor([[79.7848]], grad_fn=<AddBackward0>)
tensor([[88.4287]], grad_fn=<Add

tensor([[80.2487]], grad_fn=<AddBackward0>)
tensor([[89.6476]], grad_fn=<AddBackward0>)
tensor([[82.8424]], grad_fn=<AddBackward0>)
tensor([[80.8736]], grad_fn=<AddBackward0>)
tensor([[79.1958]], grad_fn=<AddBackward0>)
tensor([[79.5478]], grad_fn=<AddBackward0>)
tensor([[83.4202]], grad_fn=<AddBackward0>)
tensor([[82.9019]], grad_fn=<AddBackward0>)
tensor([[77.7081]], grad_fn=<AddBackward0>)
tensor([[84.4303]], grad_fn=<AddBackward0>)
tensor([[82.6919]], grad_fn=<AddBackward0>)
tensor([[78.8183]], grad_fn=<AddBackward0>)
tensor([[88.8822]], grad_fn=<AddBackward0>)
tensor([[81.0069]], grad_fn=<AddBackward0>)
tensor([[85.6127]], grad_fn=<AddBackward0>)
tensor([[76.0125]], grad_fn=<AddBackward0>)
tensor([[84.7969]], grad_fn=<AddBackward0>)
tensor([[78.9468]], grad_fn=<AddBackward0>)
tensor([[77.6710]], grad_fn=<AddBackward0>)
tensor([[81.7139]], grad_fn=<AddBackward0>)
tensor([[82.2316]], grad_fn=<AddBackward0>)
tensor([[84.2813]], grad_fn=<AddBackward0>)
tensor([[82.7393]], grad_fn=<Add

tensor([[76.3604]], grad_fn=<AddBackward0>)
tensor([[78.9971]], grad_fn=<AddBackward0>)
tensor([[83.5663]], grad_fn=<AddBackward0>)
tensor([[85.8339]], grad_fn=<AddBackward0>)
tensor([[77.6532]], grad_fn=<AddBackward0>)
tensor([[82.6485]], grad_fn=<AddBackward0>)
tensor([[79.1103]], grad_fn=<AddBackward0>)
tensor([[80.3571]], grad_fn=<AddBackward0>)
tensor([[78.6624]], grad_fn=<AddBackward0>)
tensor([[77.8396]], grad_fn=<AddBackward0>)
tensor([[76.4427]], grad_fn=<AddBackward0>)
tensor([[81.4730]], grad_fn=<AddBackward0>)
tensor([[74.3353]], grad_fn=<AddBackward0>)
tensor([[81.8457]], grad_fn=<AddBackward0>)
tensor([[89.4973]], grad_fn=<AddBackward0>)
tensor([[85.7016]], grad_fn=<AddBackward0>)
tensor([[80.5405]], grad_fn=<AddBackward0>)
tensor([[90.2143]], grad_fn=<AddBackward0>)
tensor([[83.5659]], grad_fn=<AddBackward0>)
tensor([[84.0510]], grad_fn=<AddBackward0>)
tensor([[81.8816]], grad_fn=<AddBackward0>)
tensor([[81.2301]], grad_fn=<AddBackward0>)
tensor([[86.8808]], grad_fn=<Add

tensor([[81.3990]], grad_fn=<AddBackward0>)
tensor([[81.4017]], grad_fn=<AddBackward0>)
tensor([[85.1416]], grad_fn=<AddBackward0>)
tensor([[80.4313]], grad_fn=<AddBackward0>)
tensor([[78.9591]], grad_fn=<AddBackward0>)
tensor([[84.1741]], grad_fn=<AddBackward0>)
tensor([[81.5658]], grad_fn=<AddBackward0>)
tensor([[81.5344]], grad_fn=<AddBackward0>)
tensor([[78.9613]], grad_fn=<AddBackward0>)
tensor([[80.7137]], grad_fn=<AddBackward0>)
tensor([[77.4668]], grad_fn=<AddBackward0>)
tensor([[75.4558]], grad_fn=<AddBackward0>)
tensor([[82.4935]], grad_fn=<AddBackward0>)
tensor([[77.9622]], grad_fn=<AddBackward0>)
tensor([[91.7452]], grad_fn=<AddBackward0>)
tensor([[82.7440]], grad_fn=<AddBackward0>)
tensor([[75.3063]], grad_fn=<AddBackward0>)
tensor([[80.1816]], grad_fn=<AddBackward0>)
tensor([[83.3819]], grad_fn=<AddBackward0>)
tensor([[87.9379]], grad_fn=<AddBackward0>)
tensor([[78.0443]], grad_fn=<AddBackward0>)
tensor([[82.2823]], grad_fn=<AddBackward0>)
tensor([[79.5353]], grad_fn=<Add

tensor([[85.7327]], grad_fn=<AddBackward0>)
tensor([[82.8803]], grad_fn=<AddBackward0>)
tensor([[81.9271]], grad_fn=<AddBackward0>)
tensor([[80.6997]], grad_fn=<AddBackward0>)
tensor([[84.4316]], grad_fn=<AddBackward0>)
tensor([[80.4152]], grad_fn=<AddBackward0>)
tensor([[77.7000]], grad_fn=<AddBackward0>)
tensor([[82.2191]], grad_fn=<AddBackward0>)
tensor([[82.9028]], grad_fn=<AddBackward0>)
tensor([[79.1921]], grad_fn=<AddBackward0>)
tensor([[79.4341]], grad_fn=<AddBackward0>)
tensor([[78.2639]], grad_fn=<AddBackward0>)
tensor([[74.5010]], grad_fn=<AddBackward0>)
tensor([[83.1656]], grad_fn=<AddBackward0>)
tensor([[80.0284]], grad_fn=<AddBackward0>)
tensor([[78.0601]], grad_fn=<AddBackward0>)
tensor([[82.0204]], grad_fn=<AddBackward0>)
tensor([[75.8266]], grad_fn=<AddBackward0>)
tensor([[74.7519]], grad_fn=<AddBackward0>)
tensor([[76.9084]], grad_fn=<AddBackward0>)
tensor([[81.0427]], grad_fn=<AddBackward0>)
tensor([[78.4154]], grad_fn=<AddBackward0>)
tensor([[86.5913]], grad_fn=<Add

tensor([[81.1019]], grad_fn=<AddBackward0>)
tensor([[85.4686]], grad_fn=<AddBackward0>)
tensor([[82.6607]], grad_fn=<AddBackward0>)
tensor([[79.2022]], grad_fn=<AddBackward0>)
tensor([[84.2561]], grad_fn=<AddBackward0>)
tensor([[77.7243]], grad_fn=<AddBackward0>)
tensor([[87.2240]], grad_fn=<AddBackward0>)
tensor([[78.3136]], grad_fn=<AddBackward0>)
tensor([[78.1912]], grad_fn=<AddBackward0>)
tensor([[74.1919]], grad_fn=<AddBackward0>)
tensor([[81.9808]], grad_fn=<AddBackward0>)
tensor([[80.1474]], grad_fn=<AddBackward0>)
tensor([[83.8564]], grad_fn=<AddBackward0>)
tensor([[86.2131]], grad_fn=<AddBackward0>)
tensor([[80.7947]], grad_fn=<AddBackward0>)
tensor([[84.8933]], grad_fn=<AddBackward0>)
tensor([[82.7631]], grad_fn=<AddBackward0>)
tensor([[81.4864]], grad_fn=<AddBackward0>)
tensor([[80.0879]], grad_fn=<AddBackward0>)
tensor([[85.6331]], grad_fn=<AddBackward0>)
tensor([[79.5940]], grad_fn=<AddBackward0>)
tensor([[76.7236]], grad_fn=<AddBackward0>)
tensor([[82.0689]], grad_fn=<Add

tensor([[85.0335]], grad_fn=<AddBackward0>)
tensor([[76.8957]], grad_fn=<AddBackward0>)
tensor([[79.0210]], grad_fn=<AddBackward0>)
tensor([[83.5714]], grad_fn=<AddBackward0>)
tensor([[74.3343]], grad_fn=<AddBackward0>)
tensor([[79.2784]], grad_fn=<AddBackward0>)
tensor([[81.4178]], grad_fn=<AddBackward0>)
tensor([[85.9105]], grad_fn=<AddBackward0>)
tensor([[80.0186]], grad_fn=<AddBackward0>)
tensor([[86.8383]], grad_fn=<AddBackward0>)
tensor([[81.9914]], grad_fn=<AddBackward0>)
tensor([[79.0135]], grad_fn=<AddBackward0>)
tensor([[81.5400]], grad_fn=<AddBackward0>)
tensor([[76.7704]], grad_fn=<AddBackward0>)
tensor([[86.0862]], grad_fn=<AddBackward0>)
tensor([[78.3058]], grad_fn=<AddBackward0>)
tensor([[79.6557]], grad_fn=<AddBackward0>)
tensor([[73.9511]], grad_fn=<AddBackward0>)
tensor([[80.0667]], grad_fn=<AddBackward0>)
tensor([[79.4045]], grad_fn=<AddBackward0>)
tensor([[84.4561]], grad_fn=<AddBackward0>)
tensor([[86.3524]], grad_fn=<AddBackward0>)
tensor([[78.4416]], grad_fn=<Add

tensor([[81.5618]], grad_fn=<AddBackward0>)
tensor([[78.4626]], grad_fn=<AddBackward0>)
tensor([[77.4086]], grad_fn=<AddBackward0>)
tensor([[78.8150]], grad_fn=<AddBackward0>)
tensor([[79.8366]], grad_fn=<AddBackward0>)
tensor([[83.0744]], grad_fn=<AddBackward0>)
tensor([[80.1441]], grad_fn=<AddBackward0>)
tensor([[82.9744]], grad_fn=<AddBackward0>)
tensor([[76.4503]], grad_fn=<AddBackward0>)
tensor([[77.0697]], grad_fn=<AddBackward0>)
tensor([[78.6734]], grad_fn=<AddBackward0>)
tensor([[86.1966]], grad_fn=<AddBackward0>)
tensor([[79.7052]], grad_fn=<AddBackward0>)
tensor([[79.2564]], grad_fn=<AddBackward0>)
tensor([[85.1339]], grad_fn=<AddBackward0>)
tensor([[76.3194]], grad_fn=<AddBackward0>)
tensor([[79.3518]], grad_fn=<AddBackward0>)
tensor([[81.7861]], grad_fn=<AddBackward0>)
tensor([[75.2036]], grad_fn=<AddBackward0>)
tensor([[77.7692]], grad_fn=<AddBackward0>)
tensor([[80.1419]], grad_fn=<AddBackward0>)
tensor([[88.6085]], grad_fn=<AddBackward0>)
tensor([[79.0835]], grad_fn=<Add

tensor([[74.1796]], grad_fn=<AddBackward0>)
tensor([[77.9814]], grad_fn=<AddBackward0>)
tensor([[88.4507]], grad_fn=<AddBackward0>)
tensor([[84.3689]], grad_fn=<AddBackward0>)
tensor([[75.9569]], grad_fn=<AddBackward0>)
tensor([[83.2720]], grad_fn=<AddBackward0>)
tensor([[78.9990]], grad_fn=<AddBackward0>)
tensor([[80.5993]], grad_fn=<AddBackward0>)
tensor([[77.7231]], grad_fn=<AddBackward0>)
tensor([[78.5570]], grad_fn=<AddBackward0>)
tensor([[82.7810]], grad_fn=<AddBackward0>)
tensor([[80.7431]], grad_fn=<AddBackward0>)
tensor([[78.2652]], grad_fn=<AddBackward0>)
tensor([[81.1082]], grad_fn=<AddBackward0>)
tensor([[80.6375]], grad_fn=<AddBackward0>)
tensor([[78.5429]], grad_fn=<AddBackward0>)
tensor([[87.8455]], grad_fn=<AddBackward0>)
tensor([[78.2423]], grad_fn=<AddBackward0>)
tensor([[84.8801]], grad_fn=<AddBackward0>)
tensor([[75.1507]], grad_fn=<AddBackward0>)
tensor([[83.1158]], grad_fn=<AddBackward0>)
tensor([[78.4217]], grad_fn=<AddBackward0>)
tensor([[78.7283]], grad_fn=<Add

tensor([[79.2898]], grad_fn=<AddBackward0>)
tensor([[82.4009]], grad_fn=<AddBackward0>)
tensor([[79.6178]], grad_fn=<AddBackward0>)
tensor([[76.2266]], grad_fn=<AddBackward0>)
tensor([[80.8167]], grad_fn=<AddBackward0>)
tensor([[77.0085]], grad_fn=<AddBackward0>)
tensor([[74.2295]], grad_fn=<AddBackward0>)
tensor([[83.2018]], grad_fn=<AddBackward0>)
tensor([[76.6472]], grad_fn=<AddBackward0>)
tensor([[90.4481]], grad_fn=<AddBackward0>)
tensor([[80.5814]], grad_fn=<AddBackward0>)
tensor([[73.4755]], grad_fn=<AddBackward0>)
tensor([[80.4814]], grad_fn=<AddBackward0>)
tensor([[81.1286]], grad_fn=<AddBackward0>)
tensor([[85.1985]], grad_fn=<AddBackward0>)
tensor([[76.1971]], grad_fn=<AddBackward0>)
tensor([[80.4780]], grad_fn=<AddBackward0>)
tensor([[78.5128]], grad_fn=<AddBackward0>)
tensor([[78.1571]], grad_fn=<AddBackward0>)
tensor([[76.6216]], grad_fn=<AddBackward0>)
tensor([[78.4712]], grad_fn=<AddBackward0>)
tensor([[77.4752]], grad_fn=<AddBackward0>)
tensor([[78.9887]], grad_fn=<Add

tensor([[79.8153]], grad_fn=<AddBackward0>)
tensor([[75.1281]], grad_fn=<AddBackward0>)
tensor([[77.1893]], grad_fn=<AddBackward0>)
tensor([[76.6134]], grad_fn=<AddBackward0>)
tensor([[73.1717]], grad_fn=<AddBackward0>)
tensor([[82.1718]], grad_fn=<AddBackward0>)
tensor([[79.1050]], grad_fn=<AddBackward0>)
tensor([[75.3565]], grad_fn=<AddBackward0>)
tensor([[79.0277]], grad_fn=<AddBackward0>)
tensor([[74.5463]], grad_fn=<AddBackward0>)
tensor([[76.5950]], grad_fn=<AddBackward0>)
tensor([[76.7312]], grad_fn=<AddBackward0>)
tensor([[81.2532]], grad_fn=<AddBackward0>)
tensor([[77.9377]], grad_fn=<AddBackward0>)
tensor([[79.7458]], grad_fn=<AddBackward0>)
tensor([[77.1456]], grad_fn=<AddBackward0>)
tensor([[78.0867]], grad_fn=<AddBackward0>)
tensor([[80.1019]], grad_fn=<AddBackward0>)
tensor([[83.6361]], grad_fn=<AddBackward0>)
tensor([[80.1142]], grad_fn=<AddBackward0>)
tensor([[76.5419]], grad_fn=<AddBackward0>)
tensor([[79.3820]], grad_fn=<AddBackward0>)
tensor([[76.4410]], grad_fn=<Add

tensor([[87.3572]], grad_fn=<AddBackward0>)
tensor([[79.2374]], grad_fn=<AddBackward0>)
tensor([[76.7467]], grad_fn=<AddBackward0>)
tensor([[75.1248]], grad_fn=<AddBackward0>)
tensor([[80.1457]], grad_fn=<AddBackward0>)
tensor([[77.6746]], grad_fn=<AddBackward0>)
tensor([[80.5913]], grad_fn=<AddBackward0>)
tensor([[86.0985]], grad_fn=<AddBackward0>)
tensor([[77.4072]], grad_fn=<AddBackward0>)
tensor([[80.3202]], grad_fn=<AddBackward0>)
tensor([[85.6925]], grad_fn=<AddBackward0>)
tensor([[76.6796]], grad_fn=<AddBackward0>)
tensor([[77.1215]], grad_fn=<AddBackward0>)
tensor([[81.2225]], grad_fn=<AddBackward0>)
tensor([[76.6856]], grad_fn=<AddBackward0>)
tensor([[74.3359]], grad_fn=<AddBackward0>)
tensor([[79.2031]], grad_fn=<AddBackward0>)
tensor([[82.0444]], grad_fn=<AddBackward0>)
tensor([[74.8516]], grad_fn=<AddBackward0>)
tensor([[76.8067]], grad_fn=<AddBackward0>)
tensor([[76.1444]], grad_fn=<AddBackward0>)
tensor([[72.9019]], grad_fn=<AddBackward0>)
tensor([[80.9398]], grad_fn=<Add

tensor([[71.6143]], grad_fn=<AddBackward0>)
tensor([[74.6876]], grad_fn=<AddBackward0>)
tensor([[77.5506]], grad_fn=<AddBackward0>)
tensor([[83.4046]], grad_fn=<AddBackward0>)
tensor([[78.3976]], grad_fn=<AddBackward0>)
tensor([[82.8028]], grad_fn=<AddBackward0>)
tensor([[80.3942]], grad_fn=<AddBackward0>)
tensor([[77.0573]], grad_fn=<AddBackward0>)
tensor([[81.6371]], grad_fn=<AddBackward0>)
tensor([[75.3000]], grad_fn=<AddBackward0>)
tensor([[85.9951]], grad_fn=<AddBackward0>)
tensor([[78.7224]], grad_fn=<AddBackward0>)
tensor([[76.0006]], grad_fn=<AddBackward0>)
tensor([[72.9730]], grad_fn=<AddBackward0>)
tensor([[79.4196]], grad_fn=<AddBackward0>)
tensor([[75.8903]], grad_fn=<AddBackward0>)
tensor([[80.0941]], grad_fn=<AddBackward0>)
tensor([[84.9894]], grad_fn=<AddBackward0>)
tensor([[76.3728]], grad_fn=<AddBackward0>)
tensor([[78.5635]], grad_fn=<AddBackward0>)
tensor([[84.2628]], grad_fn=<AddBackward0>)
tensor([[79.1011]], grad_fn=<AddBackward0>)
tensor([[76.5973]], grad_fn=<Add

tensor([[78.8772]], grad_fn=<AddBackward0>)
tensor([[86.0686]], grad_fn=<AddBackward0>)
tensor([[77.4658]], grad_fn=<AddBackward0>)
tensor([[85.5642]], grad_fn=<AddBackward0>)
tensor([[74.9142]], grad_fn=<AddBackward0>)
tensor([[82.8031]], grad_fn=<AddBackward0>)
tensor([[77.3048]], grad_fn=<AddBackward0>)
tensor([[76.6326]], grad_fn=<AddBackward0>)
tensor([[76.3628]], grad_fn=<AddBackward0>)
tensor([[79.1518]], grad_fn=<AddBackward0>)
tensor([[80.6881]], grad_fn=<AddBackward0>)
tensor([[80.1675]], grad_fn=<AddBackward0>)
tensor([[81.1536]], grad_fn=<AddBackward0>)
tensor([[75.2297]], grad_fn=<AddBackward0>)
tensor([[75.7937]], grad_fn=<AddBackward0>)
tensor([[77.4119]], grad_fn=<AddBackward0>)
tensor([[80.4582]], grad_fn=<AddBackward0>)
tensor([[78.9567]], grad_fn=<AddBackward0>)
tensor([[79.1265]], grad_fn=<AddBackward0>)
tensor([[85.4801]], grad_fn=<AddBackward0>)
tensor([[73.4511]], grad_fn=<AddBackward0>)
tensor([[77.8397]], grad_fn=<AddBackward0>)
tensor([[81.3728]], grad_fn=<Add

tensor([[75.8208]], grad_fn=<AddBackward0>)
tensor([[87.1600]], grad_fn=<AddBackward0>)
tensor([[80.3080]], grad_fn=<AddBackward0>)
tensor([[75.3082]], grad_fn=<AddBackward0>)
tensor([[82.0469]], grad_fn=<AddBackward0>)
tensor([[77.3018]], grad_fn=<AddBackward0>)
tensor([[77.0955]], grad_fn=<AddBackward0>)
tensor([[77.0638]], grad_fn=<AddBackward0>)
tensor([[78.2916]], grad_fn=<AddBackward0>)
tensor([[85.7312]], grad_fn=<AddBackward0>)
tensor([[80.2413]], grad_fn=<AddBackward0>)
tensor([[76.7944]], grad_fn=<AddBackward0>)
tensor([[79.7502]], grad_fn=<AddBackward0>)
tensor([[78.6193]], grad_fn=<AddBackward0>)
tensor([[76.6540]], grad_fn=<AddBackward0>)
tensor([[86.9958]], grad_fn=<AddBackward0>)
tensor([[78.3830]], grad_fn=<AddBackward0>)
tensor([[83.0111]], grad_fn=<AddBackward0>)
tensor([[73.0815]], grad_fn=<AddBackward0>)
tensor([[81.8398]], grad_fn=<AddBackward0>)
tensor([[76.9506]], grad_fn=<AddBackward0>)
tensor([[75.2235]], grad_fn=<AddBackward0>)
tensor([[76.3561]], grad_fn=<Add

tensor([[71.1831]], grad_fn=<AddBackward0>)
tensor([[79.9837]], grad_fn=<AddBackward0>)
tensor([[75.1394]], grad_fn=<AddBackward0>)
tensor([[84.2843]], grad_fn=<AddBackward0>)
tensor([[79.4940]], grad_fn=<AddBackward0>)
tensor([[71.9326]], grad_fn=<AddBackward0>)
tensor([[79.6537]], grad_fn=<AddBackward0>)
tensor([[81.8827]], grad_fn=<AddBackward0>)
tensor([[85.6538]], grad_fn=<AddBackward0>)
tensor([[73.8761]], grad_fn=<AddBackward0>)
tensor([[78.9439]], grad_fn=<AddBackward0>)
tensor([[76.5362]], grad_fn=<AddBackward0>)
tensor([[77.1279]], grad_fn=<AddBackward0>)
tensor([[75.1849]], grad_fn=<AddBackward0>)
tensor([[76.9868]], grad_fn=<AddBackward0>)
tensor([[74.9531]], grad_fn=<AddBackward0>)
tensor([[78.7118]], grad_fn=<AddBackward0>)
tensor([[73.7490]], grad_fn=<AddBackward0>)
tensor([[74.8990]], grad_fn=<AddBackward0>)
tensor([[86.0926]], grad_fn=<AddBackward0>)
tensor([[79.3590]], grad_fn=<AddBackward0>)
tensor([[74.6563]], grad_fn=<AddBackward0>)
tensor([[80.8075]], grad_fn=<Add

tensor([[74.6770]], grad_fn=<AddBackward0>)
tensor([[78.3085]], grad_fn=<AddBackward0>)
tensor([[82.9663]], grad_fn=<AddBackward0>)
tensor([[75.0035]], grad_fn=<AddBackward0>)
tensor([[77.0063]], grad_fn=<AddBackward0>)
tensor([[75.8779]], grad_fn=<AddBackward0>)
tensor([[76.5030]], grad_fn=<AddBackward0>)
tensor([[74.4813]], grad_fn=<AddBackward0>)
tensor([[79.9145]], grad_fn=<AddBackward0>)
tensor([[76.8785]], grad_fn=<AddBackward0>)
tensor([[75.5731]], grad_fn=<AddBackward0>)
tensor([[77.1104]], grad_fn=<AddBackward0>)
tensor([[73.7921]], grad_fn=<AddBackward0>)
tensor([[71.1573]], grad_fn=<AddBackward0>)
tensor([[78.9667]], grad_fn=<AddBackward0>)
tensor([[74.4693]], grad_fn=<AddBackward0>)
tensor([[84.4928]], grad_fn=<AddBackward0>)
tensor([[79.4618]], grad_fn=<AddBackward0>)
tensor([[71.2295]], grad_fn=<AddBackward0>)
tensor([[79.1079]], grad_fn=<AddBackward0>)
tensor([[80.2268]], grad_fn=<AddBackward0>)
tensor([[86.0023]], grad_fn=<AddBackward0>)
tensor([[72.5074]], grad_fn=<Add

tensor([[73.7898]], grad_fn=<AddBackward0>)
tensor([[78.5036]], grad_fn=<AddBackward0>)
tensor([[81.4864]], grad_fn=<AddBackward0>)
tensor([[77.4705]], grad_fn=<AddBackward0>)
tensor([[75.2942]], grad_fn=<AddBackward0>)
tensor([[86.9062]], grad_fn=<AddBackward0>)
tensor([[81.1011]], grad_fn=<AddBackward0>)
tensor([[74.6491]], grad_fn=<AddBackward0>)
tensor([[79.9210]], grad_fn=<AddBackward0>)
tensor([[77.4318]], grad_fn=<AddBackward0>)
tensor([[75.8199]], grad_fn=<AddBackward0>)
tensor([[80.5948]], grad_fn=<AddBackward0>)
tensor([[78.4518]], grad_fn=<AddBackward0>)
tensor([[77.1375]], grad_fn=<AddBackward0>)
tensor([[76.2871]], grad_fn=<AddBackward0>)
tensor([[75.1051]], grad_fn=<AddBackward0>)
tensor([[73.8269]], grad_fn=<AddBackward0>)
tensor([[78.9001]], grad_fn=<AddBackward0>)
tensor([[80.9531]], grad_fn=<AddBackward0>)
tensor([[74.3523]], grad_fn=<AddBackward0>)
tensor([[78.1223]], grad_fn=<AddBackward0>)
tensor([[76.1585]], grad_fn=<AddBackward0>)
tensor([[73.4774]], grad_fn=<Add

tensor([[79.8944]], grad_fn=<AddBackward0>)
tensor([[78.1126]], grad_fn=<AddBackward0>)
tensor([[76.5872]], grad_fn=<AddBackward0>)
tensor([[86.6914]], grad_fn=<AddBackward0>)
tensor([[75.8214]], grad_fn=<AddBackward0>)
tensor([[74.4426]], grad_fn=<AddBackward0>)
tensor([[73.5738]], grad_fn=<AddBackward0>)
tensor([[78.7319]], grad_fn=<AddBackward0>)
tensor([[73.6988]], grad_fn=<AddBackward0>)
tensor([[78.0017]], grad_fn=<AddBackward0>)
tensor([[79.9259]], grad_fn=<AddBackward0>)
tensor([[75.6243]], grad_fn=<AddBackward0>)
tensor([[74.0869]], grad_fn=<AddBackward0>)
tensor([[88.3432]], grad_fn=<AddBackward0>)
tensor([[78.9192]], grad_fn=<AddBackward0>)
tensor([[74.8384]], grad_fn=<AddBackward0>)
tensor([[79.4064]], grad_fn=<AddBackward0>)
tensor([[76.8733]], grad_fn=<AddBackward0>)
tensor([[76.2529]], grad_fn=<AddBackward0>)
tensor([[78.8380]], grad_fn=<AddBackward0>)
tensor([[79.8002]], grad_fn=<AddBackward0>)
tensor([[77.0851]], grad_fn=<AddBackward0>)
tensor([[76.5911]], grad_fn=<Add

tensor([[77.7236]], grad_fn=<AddBackward0>)
tensor([[79.9391]], grad_fn=<AddBackward0>)
tensor([[75.4652]], grad_fn=<AddBackward0>)
tensor([[78.3016]], grad_fn=<AddBackward0>)
tensor([[83.4671]], grad_fn=<AddBackward0>)
tensor([[70.3298]], grad_fn=<AddBackward0>)
tensor([[76.0827]], grad_fn=<AddBackward0>)
tensor([[80.3504]], grad_fn=<AddBackward0>)
tensor([[71.3689]], grad_fn=<AddBackward0>)
tensor([[75.0880]], grad_fn=<AddBackward0>)
tensor([[73.4763]], grad_fn=<AddBackward0>)
tensor([[80.8451]], grad_fn=<AddBackward0>)
tensor([[77.5541]], grad_fn=<AddBackward0>)
tensor([[80.4778]], grad_fn=<AddBackward0>)
tensor([[78.5901]], grad_fn=<AddBackward0>)
tensor([[77.9425]], grad_fn=<AddBackward0>)
tensor([[77.6965]], grad_fn=<AddBackward0>)
tensor([[74.7643]], grad_fn=<AddBackward0>)
tensor([[83.1823]], grad_fn=<AddBackward0>)
tensor([[74.4874]], grad_fn=<AddBackward0>)
tensor([[73.8436]], grad_fn=<AddBackward0>)
tensor([[73.0320]], grad_fn=<AddBackward0>)
tensor([[78.7008]], grad_fn=<Add

tensor([[80.5945]], grad_fn=<AddBackward0>)
tensor([[75.4753]], grad_fn=<AddBackward0>)
tensor([[77.8534]], grad_fn=<AddBackward0>)
tensor([[76.7404]], grad_fn=<AddBackward0>)
tensor([[76.3796]], grad_fn=<AddBackward0>)
tensor([[87.3577]], grad_fn=<AddBackward0>)
tensor([[76.0108]], grad_fn=<AddBackward0>)
tensor([[84.6187]], grad_fn=<AddBackward0>)
tensor([[72.1573]], grad_fn=<AddBackward0>)
tensor([[78.0344]], grad_fn=<AddBackward0>)
tensor([[75.7750]], grad_fn=<AddBackward0>)
tensor([[73.5767]], grad_fn=<AddBackward0>)
tensor([[75.9487]], grad_fn=<AddBackward0>)
tensor([[77.8734]], grad_fn=<AddBackward0>)
tensor([[78.1205]], grad_fn=<AddBackward0>)
tensor([[81.0946]], grad_fn=<AddBackward0>)
tensor([[79.6311]], grad_fn=<AddBackward0>)
tensor([[75.3758]], grad_fn=<AddBackward0>)
tensor([[74.8299]], grad_fn=<AddBackward0>)
tensor([[76.5633]], grad_fn=<AddBackward0>)
tensor([[78.5219]], grad_fn=<AddBackward0>)
tensor([[76.6236]], grad_fn=<AddBackward0>)
tensor([[77.5641]], grad_fn=<Add

tensor([[75.1171]], grad_fn=<AddBackward0>)
tensor([[76.3465]], grad_fn=<AddBackward0>)
tensor([[75.7722]], grad_fn=<AddBackward0>)
tensor([[79.0541]], grad_fn=<AddBackward0>)
tensor([[73.8147]], grad_fn=<AddBackward0>)
tensor([[80.0798]], grad_fn=<AddBackward0>)
tensor([[73.5066]], grad_fn=<AddBackward0>)
tensor([[76.4001]], grad_fn=<AddBackward0>)
tensor([[86.1309]], grad_fn=<AddBackward0>)
tensor([[81.1570]], grad_fn=<AddBackward0>)
tensor([[72.1479]], grad_fn=<AddBackward0>)
tensor([[81.3269]], grad_fn=<AddBackward0>)
tensor([[76.1923]], grad_fn=<AddBackward0>)
tensor([[75.1239]], grad_fn=<AddBackward0>)
tensor([[72.6028]], grad_fn=<AddBackward0>)
tensor([[72.7777]], grad_fn=<AddBackward0>)
tensor([[85.4422]], grad_fn=<AddBackward0>)
tensor([[78.2283]], grad_fn=<AddBackward0>)
tensor([[75.9158]], grad_fn=<AddBackward0>)
tensor([[77.0510]], grad_fn=<AddBackward0>)
tensor([[75.5267]], grad_fn=<AddBackward0>)
tensor([[77.3148]], grad_fn=<AddBackward0>)
tensor([[86.0364]], grad_fn=<Add

tensor([[73.9160]], grad_fn=<AddBackward0>)
tensor([[76.8807]], grad_fn=<AddBackward0>)
tensor([[72.2108]], grad_fn=<AddBackward0>)
tensor([[79.6919]], grad_fn=<AddBackward0>)
tensor([[74.1165]], grad_fn=<AddBackward0>)
tensor([[73.5846]], grad_fn=<AddBackward0>)
tensor([[76.2508]], grad_fn=<AddBackward0>)
tensor([[73.8931]], grad_fn=<AddBackward0>)
tensor([[70.0793]], grad_fn=<AddBackward0>)
tensor([[78.2117]], grad_fn=<AddBackward0>)
tensor([[72.3837]], grad_fn=<AddBackward0>)
tensor([[82.6907]], grad_fn=<AddBackward0>)
tensor([[78.4599]], grad_fn=<AddBackward0>)
tensor([[69.6982]], grad_fn=<AddBackward0>)
tensor([[80.4610]], grad_fn=<AddBackward0>)
tensor([[79.6954]], grad_fn=<AddBackward0>)
tensor([[85.3036]], grad_fn=<AddBackward0>)
tensor([[71.9660]], grad_fn=<AddBackward0>)
tensor([[79.5093]], grad_fn=<AddBackward0>)
tensor([[74.5932]], grad_fn=<AddBackward0>)
tensor([[77.6571]], grad_fn=<AddBackward0>)
tensor([[76.3130]], grad_fn=<AddBackward0>)
tensor([[77.9178]], grad_fn=<Add

tensor([[77.2567]], grad_fn=<AddBackward0>)
tensor([[77.6520]], grad_fn=<AddBackward0>)
tensor([[76.4764]], grad_fn=<AddBackward0>)
tensor([[76.5743]], grad_fn=<AddBackward0>)
tensor([[75.8234]], grad_fn=<AddBackward0>)
tensor([[74.5510]], grad_fn=<AddBackward0>)
tensor([[78.9200]], grad_fn=<AddBackward0>)
tensor([[81.5880]], grad_fn=<AddBackward0>)
tensor([[74.4969]], grad_fn=<AddBackward0>)
tensor([[79.5112]], grad_fn=<AddBackward0>)
tensor([[74.9362]], grad_fn=<AddBackward0>)
tensor([[73.1707]], grad_fn=<AddBackward0>)
tensor([[74.9448]], grad_fn=<AddBackward0>)
tensor([[81.5519]], grad_fn=<AddBackward0>)
tensor([[74.3490]], grad_fn=<AddBackward0>)
tensor([[74.2658]], grad_fn=<AddBackward0>)
tensor([[73.6479]], grad_fn=<AddBackward0>)
tensor([[76.4373]], grad_fn=<AddBackward0>)
tensor([[72.3300]], grad_fn=<AddBackward0>)
tensor([[79.8571]], grad_fn=<AddBackward0>)
tensor([[73.8480]], grad_fn=<AddBackward0>)
tensor([[73.2191]], grad_fn=<AddBackward0>)
tensor([[75.1911]], grad_fn=<Add

tensor([[77.9110]], grad_fn=<AddBackward0>)
tensor([[77.4975]], grad_fn=<AddBackward0>)
tensor([[76.8258]], grad_fn=<AddBackward0>)
tensor([[76.0412]], grad_fn=<AddBackward0>)
tensor([[84.5358]], grad_fn=<AddBackward0>)
tensor([[73.6170]], grad_fn=<AddBackward0>)
tensor([[73.5499]], grad_fn=<AddBackward0>)
tensor([[72.7218]], grad_fn=<AddBackward0>)
tensor([[79.6755]], grad_fn=<AddBackward0>)
tensor([[73.3085]], grad_fn=<AddBackward0>)
tensor([[78.5301]], grad_fn=<AddBackward0>)
tensor([[80.8364]], grad_fn=<AddBackward0>)
tensor([[76.0345]], grad_fn=<AddBackward0>)
tensor([[75.0649]], grad_fn=<AddBackward0>)
tensor([[86.2880]], grad_fn=<AddBackward0>)
tensor([[83.8258]], grad_fn=<AddBackward0>)
tensor([[72.8697]], grad_fn=<AddBackward0>)
tensor([[76.5023]], grad_fn=<AddBackward0>)
tensor([[75.8098]], grad_fn=<AddBackward0>)
tensor([[75.5787]], grad_fn=<AddBackward0>)
tensor([[79.5632]], grad_fn=<AddBackward0>)
tensor([[79.0169]], grad_fn=<AddBackward0>)
tensor([[76.6115]], grad_fn=<Add

tensor([[78.9082]], grad_fn=<AddBackward0>)
tensor([[76.5038]], grad_fn=<AddBackward0>)
tensor([[76.2076]], grad_fn=<AddBackward0>)
tensor([[73.1260]], grad_fn=<AddBackward0>)
tensor([[75.3971]], grad_fn=<AddBackward0>)
tensor([[75.2208]], grad_fn=<AddBackward0>)
tensor([[73.9820]], grad_fn=<AddBackward0>)
tensor([[77.6665]], grad_fn=<AddBackward0>)
tensor([[80.4934]], grad_fn=<AddBackward0>)
tensor([[69.7150]], grad_fn=<AddBackward0>)
tensor([[75.7346]], grad_fn=<AddBackward0>)
tensor([[78.4399]], grad_fn=<AddBackward0>)
tensor([[70.8144]], grad_fn=<AddBackward0>)
tensor([[71.3766]], grad_fn=<AddBackward0>)
tensor([[71.6562]], grad_fn=<AddBackward0>)
tensor([[79.3845]], grad_fn=<AddBackward0>)
tensor([[76.5177]], grad_fn=<AddBackward0>)
tensor([[79.0827]], grad_fn=<AddBackward0>)
tensor([[78.0005]], grad_fn=<AddBackward0>)
tensor([[77.6786]], grad_fn=<AddBackward0>)
tensor([[76.0782]], grad_fn=<AddBackward0>)
tensor([[74.4722]], grad_fn=<AddBackward0>)
tensor([[84.5899]], grad_fn=<Add

tensor([[77.8934]], grad_fn=<AddBackward0>)
tensor([[75.9897]], grad_fn=<AddBackward0>)
tensor([[76.4519]], grad_fn=<AddBackward0>)
tensor([[84.7537]], grad_fn=<AddBackward0>)
tensor([[75.0456]], grad_fn=<AddBackward0>)
tensor([[84.5361]], grad_fn=<AddBackward0>)
tensor([[71.1966]], grad_fn=<AddBackward0>)
tensor([[79.9530]], grad_fn=<AddBackward0>)
tensor([[74.9532]], grad_fn=<AddBackward0>)
tensor([[73.7745]], grad_fn=<AddBackward0>)
tensor([[76.0109]], grad_fn=<AddBackward0>)
tensor([[77.2865]], grad_fn=<AddBackward0>)
tensor([[75.6169]], grad_fn=<AddBackward0>)
tensor([[78.5898]], grad_fn=<AddBackward0>)
tensor([[75.7770]], grad_fn=<AddBackward0>)
tensor([[75.7745]], grad_fn=<AddBackward0>)
tensor([[73.0174]], grad_fn=<AddBackward0>)
tensor([[75.8076]], grad_fn=<AddBackward0>)
tensor([[75.9886]], grad_fn=<AddBackward0>)
tensor([[73.8530]], grad_fn=<AddBackward0>)
tensor([[77.7670]], grad_fn=<AddBackward0>)
tensor([[81.9141]], grad_fn=<AddBackward0>)
tensor([[69.8881]], grad_fn=<Add

tensor([[77.0017]], grad_fn=<AddBackward0>)
tensor([[70.0758]], grad_fn=<AddBackward0>)
tensor([[72.1808]], grad_fn=<AddBackward0>)
tensor([[79.3115]], grad_fn=<AddBackward0>)
tensor([[74.3090]], grad_fn=<AddBackward0>)
tensor([[70.0791]], grad_fn=<AddBackward0>)
tensor([[78.2926]], grad_fn=<AddBackward0>)
tensor([[72.7645]], grad_fn=<AddBackward0>)
tensor([[73.8825]], grad_fn=<AddBackward0>)
tensor([[73.2336]], grad_fn=<AddBackward0>)
tensor([[73.3148]], grad_fn=<AddBackward0>)
tensor([[83.6380]], grad_fn=<AddBackward0>)
tensor([[78.1564]], grad_fn=<AddBackward0>)
tensor([[74.1216]], grad_fn=<AddBackward0>)
tensor([[78.2865]], grad_fn=<AddBackward0>)
tensor([[76.6221]], grad_fn=<AddBackward0>)
tensor([[77.2858]], grad_fn=<AddBackward0>)
tensor([[86.7127]], grad_fn=<AddBackward0>)
tensor([[75.2152]], grad_fn=<AddBackward0>)
tensor([[84.2725]], grad_fn=<AddBackward0>)
tensor([[71.0305]], grad_fn=<AddBackward0>)
tensor([[81.0390]], grad_fn=<AddBackward0>)
tensor([[75.0523]], grad_fn=<Add

tensor([[78.2457]], grad_fn=<AddBackward0>)
tensor([[84.9229]], grad_fn=<AddBackward0>)
tensor([[70.6051]], grad_fn=<AddBackward0>)
tensor([[79.0465]], grad_fn=<AddBackward0>)
tensor([[73.0907]], grad_fn=<AddBackward0>)
tensor([[75.1991]], grad_fn=<AddBackward0>)
tensor([[73.7267]], grad_fn=<AddBackward0>)
tensor([[73.9432]], grad_fn=<AddBackward0>)
tensor([[71.4524]], grad_fn=<AddBackward0>)
tensor([[78.3828]], grad_fn=<AddBackward0>)
tensor([[70.7119]], grad_fn=<AddBackward0>)
tensor([[72.4179]], grad_fn=<AddBackward0>)
tensor([[78.3217]], grad_fn=<AddBackward0>)
tensor([[75.3916]], grad_fn=<AddBackward0>)
tensor([[69.7095]], grad_fn=<AddBackward0>)
tensor([[77.1491]], grad_fn=<AddBackward0>)
tensor([[71.8059]], grad_fn=<AddBackward0>)
tensor([[72.7396]], grad_fn=<AddBackward0>)
tensor([[73.1360]], grad_fn=<AddBackward0>)
tensor([[72.5025]], grad_fn=<AddBackward0>)
tensor([[82.4286]], grad_fn=<AddBackward0>)
tensor([[76.7487]], grad_fn=<AddBackward0>)
tensor([[73.9827]], grad_fn=<Add

tensor([[79.6522]], grad_fn=<AddBackward0>)
tensor([[73.2269]], grad_fn=<AddBackward0>)
tensor([[74.3096]], grad_fn=<AddBackward0>)
tensor([[72.8645]], grad_fn=<AddBackward0>)
tensor([[73.6840]], grad_fn=<AddBackward0>)
tensor([[70.6517]], grad_fn=<AddBackward0>)
tensor([[78.1120]], grad_fn=<AddBackward0>)
tensor([[73.7005]], grad_fn=<AddBackward0>)
tensor([[72.8707]], grad_fn=<AddBackward0>)
tensor([[73.9323]], grad_fn=<AddBackward0>)
tensor([[74.9284]], grad_fn=<AddBackward0>)
tensor([[69.0015]], grad_fn=<AddBackward0>)
tensor([[79.1019]], grad_fn=<AddBackward0>)
tensor([[73.2564]], grad_fn=<AddBackward0>)
tensor([[81.9791]], grad_fn=<AddBackward0>)
tensor([[78.0408]], grad_fn=<AddBackward0>)
tensor([[70.7234]], grad_fn=<AddBackward0>)
tensor([[75.0401]], grad_fn=<AddBackward0>)
tensor([[77.7318]], grad_fn=<AddBackward0>)
tensor([[84.0213]], grad_fn=<AddBackward0>)
tensor([[69.9357]], grad_fn=<AddBackward0>)
tensor([[78.6124]], grad_fn=<AddBackward0>)
tensor([[72.6833]], grad_fn=<Add

tensor([[76.1594]], grad_fn=<AddBackward0>)
tensor([[73.4619]], grad_fn=<AddBackward0>)
tensor([[74.8596]], grad_fn=<AddBackward0>)
tensor([[74.7806]], grad_fn=<AddBackward0>)
tensor([[72.6925]], grad_fn=<AddBackward0>)
tensor([[79.3865]], grad_fn=<AddBackward0>)
tensor([[77.7529]], grad_fn=<AddBackward0>)
tensor([[75.0116]], grad_fn=<AddBackward0>)
tensor([[78.8698]], grad_fn=<AddBackward0>)
tensor([[75.1264]], grad_fn=<AddBackward0>)
tensor([[71.2638]], grad_fn=<AddBackward0>)
tensor([[73.7524]], grad_fn=<AddBackward0>)
tensor([[80.8526]], grad_fn=<AddBackward0>)
tensor([[72.5274]], grad_fn=<AddBackward0>)
tensor([[73.4704]], grad_fn=<AddBackward0>)
tensor([[72.2767]], grad_fn=<AddBackward0>)
tensor([[72.3665]], grad_fn=<AddBackward0>)
tensor([[71.6151]], grad_fn=<AddBackward0>)
tensor([[77.2374]], grad_fn=<AddBackward0>)
tensor([[72.7023]], grad_fn=<AddBackward0>)
tensor([[72.8498]], grad_fn=<AddBackward0>)
tensor([[74.6795]], grad_fn=<AddBackward0>)
tensor([[74.7770]], grad_fn=<Add

tensor([[78.5118]], grad_fn=<AddBackward0>)
tensor([[73.4960]], grad_fn=<AddBackward0>)
tensor([[79.2026]], grad_fn=<AddBackward0>)
tensor([[82.7348]], grad_fn=<AddBackward0>)
tensor([[74.6410]], grad_fn=<AddBackward0>)
tensor([[74.9119]], grad_fn=<AddBackward0>)
tensor([[83.6685]], grad_fn=<AddBackward0>)
tensor([[82.5299]], grad_fn=<AddBackward0>)
tensor([[70.7554]], grad_fn=<AddBackward0>)
tensor([[76.1386]], grad_fn=<AddBackward0>)
tensor([[72.4608]], grad_fn=<AddBackward0>)
tensor([[72.5343]], grad_fn=<AddBackward0>)
tensor([[77.2179]], grad_fn=<AddBackward0>)
tensor([[74.7327]], grad_fn=<AddBackward0>)
tensor([[72.2345]], grad_fn=<AddBackward0>)
tensor([[74.6874]], grad_fn=<AddBackward0>)
tensor([[75.3896]], grad_fn=<AddBackward0>)
tensor([[71.6408]], grad_fn=<AddBackward0>)
tensor([[80.2798]], grad_fn=<AddBackward0>)
tensor([[76.9834]], grad_fn=<AddBackward0>)
tensor([[74.5069]], grad_fn=<AddBackward0>)
tensor([[78.1506]], grad_fn=<AddBackward0>)
tensor([[75.5220]], grad_fn=<Add

tensor([[69.5877]], grad_fn=<AddBackward0>)
tensor([[75.6332]], grad_fn=<AddBackward0>)
tensor([[78.1130]], grad_fn=<AddBackward0>)
tensor([[69.3163]], grad_fn=<AddBackward0>)
tensor([[68.8373]], grad_fn=<AddBackward0>)
tensor([[72.2986]], grad_fn=<AddBackward0>)
tensor([[78.1402]], grad_fn=<AddBackward0>)
tensor([[75.1186]], grad_fn=<AddBackward0>)
tensor([[77.6819]], grad_fn=<AddBackward0>)
tensor([[76.3995]], grad_fn=<AddBackward0>)
tensor([[74.8320]], grad_fn=<AddBackward0>)
tensor([[76.2761]], grad_fn=<AddBackward0>)
tensor([[73.3219]], grad_fn=<AddBackward0>)
tensor([[82.9395]], grad_fn=<AddBackward0>)
tensor([[73.3546]], grad_fn=<AddBackward0>)
tensor([[73.1803]], grad_fn=<AddBackward0>)
tensor([[70.4464]], grad_fn=<AddBackward0>)
tensor([[77.4309]], grad_fn=<AddBackward0>)
tensor([[73.0257]], grad_fn=<AddBackward0>)
tensor([[78.5631]], grad_fn=<AddBackward0>)
tensor([[82.9652]], grad_fn=<AddBackward0>)
tensor([[74.7920]], grad_fn=<AddBackward0>)
tensor([[75.6102]], grad_fn=<Add

tensor([[79.4122]], grad_fn=<AddBackward0>)
tensor([[71.3630]], grad_fn=<AddBackward0>)
tensor([[74.0467]], grad_fn=<AddBackward0>)
tensor([[73.8077]], grad_fn=<AddBackward0>)
tensor([[76.0151]], grad_fn=<AddBackward0>)
tensor([[74.2035]], grad_fn=<AddBackward0>)
tensor([[74.6224]], grad_fn=<AddBackward0>)
tensor([[73.4149]], grad_fn=<AddBackward0>)
tensor([[73.3839]], grad_fn=<AddBackward0>)
tensor([[71.0494]], grad_fn=<AddBackward0>)
tensor([[76.6664]], grad_fn=<AddBackward0>)
tensor([[71.9408]], grad_fn=<AddBackward0>)
tensor([[73.5180]], grad_fn=<AddBackward0>)
tensor([[81.6134]], grad_fn=<AddBackward0>)
tensor([[83.5117]], grad_fn=<AddBackward0>)
tensor([[70.5117]], grad_fn=<AddBackward0>)
tensor([[76.6167]], grad_fn=<AddBackward0>)
tensor([[79.7393]], grad_fn=<AddBackward0>)
tensor([[69.5338]], grad_fn=<AddBackward0>)
tensor([[69.3100]], grad_fn=<AddBackward0>)
tensor([[74.0456]], grad_fn=<AddBackward0>)
tensor([[77.8678]], grad_fn=<AddBackward0>)
tensor([[75.2353]], grad_fn=<Add

tensor([[77.9372]], grad_fn=<AddBackward0>)
tensor([[71.4029]], grad_fn=<AddBackward0>)
tensor([[73.7268]], grad_fn=<AddBackward0>)
tensor([[72.2280]], grad_fn=<AddBackward0>)
tensor([[72.6899]], grad_fn=<AddBackward0>)
tensor([[80.6621]], grad_fn=<AddBackward0>)
tensor([[74.7925]], grad_fn=<AddBackward0>)
tensor([[72.9001]], grad_fn=<AddBackward0>)
tensor([[75.2487]], grad_fn=<AddBackward0>)
tensor([[76.9702]], grad_fn=<AddBackward0>)
tensor([[76.6292]], grad_fn=<AddBackward0>)
tensor([[85.8127]], grad_fn=<AddBackward0>)
tensor([[73.2549]], grad_fn=<AddBackward0>)
tensor([[82.2738]], grad_fn=<AddBackward0>)
tensor([[72.0026]], grad_fn=<AddBackward0>)
tensor([[78.3735]], grad_fn=<AddBackward0>)
tensor([[71.8330]], grad_fn=<AddBackward0>)
tensor([[73.8031]], grad_fn=<AddBackward0>)
tensor([[75.3260]], grad_fn=<AddBackward0>)
tensor([[75.0058]], grad_fn=<AddBackward0>)
tensor([[73.3342]], grad_fn=<AddBackward0>)
tensor([[76.6333]], grad_fn=<AddBackward0>)
tensor([[73.9326]], grad_fn=<Add

tensor([[77.9637]], grad_fn=<AddBackward0>)
tensor([[82.7376]], grad_fn=<AddBackward0>)
tensor([[69.8918]], grad_fn=<AddBackward0>)
tensor([[78.2909]], grad_fn=<AddBackward0>)
tensor([[71.0431]], grad_fn=<AddBackward0>)
tensor([[74.1704]], grad_fn=<AddBackward0>)
tensor([[72.5731]], grad_fn=<AddBackward0>)
tensor([[72.1280]], grad_fn=<AddBackward0>)
tensor([[71.5760]], grad_fn=<AddBackward0>)
tensor([[75.9870]], grad_fn=<AddBackward0>)
tensor([[68.7901]], grad_fn=<AddBackward0>)
tensor([[70.6892]], grad_fn=<AddBackward0>)
tensor([[78.4622]], grad_fn=<AddBackward0>)
tensor([[73.7291]], grad_fn=<AddBackward0>)
tensor([[70.3558]], grad_fn=<AddBackward0>)
tensor([[75.7202]], grad_fn=<AddBackward0>)
tensor([[71.4905]], grad_fn=<AddBackward0>)
tensor([[72.7162]], grad_fn=<AddBackward0>)
tensor([[71.6983]], grad_fn=<AddBackward0>)
tensor([[71.5079]], grad_fn=<AddBackward0>)
tensor([[79.4017]], grad_fn=<AddBackward0>)
tensor([[73.3769]], grad_fn=<AddBackward0>)
tensor([[73.3030]], grad_fn=<Add

tensor([[77.7758]], grad_fn=<AddBackward0>)
tensor([[71.6756]], grad_fn=<AddBackward0>)
tensor([[73.3741]], grad_fn=<AddBackward0>)
tensor([[72.0864]], grad_fn=<AddBackward0>)
tensor([[73.6945]], grad_fn=<AddBackward0>)
tensor([[69.7585]], grad_fn=<AddBackward0>)
tensor([[76.0045]], grad_fn=<AddBackward0>)
tensor([[73.5748]], grad_fn=<AddBackward0>)
tensor([[72.2908]], grad_fn=<AddBackward0>)
tensor([[72.7954]], grad_fn=<AddBackward0>)
tensor([[74.7669]], grad_fn=<AddBackward0>)
tensor([[68.3307]], grad_fn=<AddBackward0>)
tensor([[76.4814]], grad_fn=<AddBackward0>)
tensor([[70.8997]], grad_fn=<AddBackward0>)
tensor([[79.7555]], grad_fn=<AddBackward0>)
tensor([[77.0312]], grad_fn=<AddBackward0>)
tensor([[69.7802]], grad_fn=<AddBackward0>)
tensor([[74.6541]], grad_fn=<AddBackward0>)
tensor([[76.4064]], grad_fn=<AddBackward0>)
tensor([[83.8117]], grad_fn=<AddBackward0>)
tensor([[69.6575]], grad_fn=<AddBackward0>)
tensor([[78.7281]], grad_fn=<AddBackward0>)
tensor([[72.7070]], grad_fn=<Add

tensor([[74.4893]], grad_fn=<AddBackward0>)
tensor([[83.2312]], grad_fn=<AddBackward0>)
tensor([[81.8468]], grad_fn=<AddBackward0>)
tensor([[69.4702]], grad_fn=<AddBackward0>)
tensor([[75.8163]], grad_fn=<AddBackward0>)
tensor([[71.7647]], grad_fn=<AddBackward0>)
tensor([[72.5165]], grad_fn=<AddBackward0>)
tensor([[74.8928]], grad_fn=<AddBackward0>)
tensor([[73.6105]], grad_fn=<AddBackward0>)
tensor([[72.5456]], grad_fn=<AddBackward0>)
tensor([[74.2199]], grad_fn=<AddBackward0>)
tensor([[74.7937]], grad_fn=<AddBackward0>)
tensor([[71.9777]], grad_fn=<AddBackward0>)
tensor([[79.7974]], grad_fn=<AddBackward0>)
tensor([[76.2792]], grad_fn=<AddBackward0>)
tensor([[73.8054]], grad_fn=<AddBackward0>)
tensor([[77.3110]], grad_fn=<AddBackward0>)
tensor([[75.1892]], grad_fn=<AddBackward0>)
tensor([[71.8671]], grad_fn=<AddBackward0>)
tensor([[71.6219]], grad_fn=<AddBackward0>)
tensor([[79.0085]], grad_fn=<AddBackward0>)
tensor([[71.6602]], grad_fn=<AddBackward0>)
tensor([[72.2433]], grad_fn=<Add

tensor([[69.8732]], grad_fn=<AddBackward0>)
tensor([[75.0562]], grad_fn=<AddBackward0>)
tensor([[79.5745]], grad_fn=<AddBackward0>)
tensor([[67.7382]], grad_fn=<AddBackward0>)
tensor([[67.6285]], grad_fn=<AddBackward0>)
tensor([[73.8480]], grad_fn=<AddBackward0>)
tensor([[74.9156]], grad_fn=<AddBackward0>)
tensor([[73.2693]], grad_fn=<AddBackward0>)
tensor([[76.9182]], grad_fn=<AddBackward0>)
tensor([[75.6421]], grad_fn=<AddBackward0>)
tensor([[75.2285]], grad_fn=<AddBackward0>)
tensor([[75.9530]], grad_fn=<AddBackward0>)
tensor([[73.5217]], grad_fn=<AddBackward0>)
tensor([[82.6186]], grad_fn=<AddBackward0>)
tensor([[74.0563]], grad_fn=<AddBackward0>)
tensor([[73.7208]], grad_fn=<AddBackward0>)
tensor([[69.2681]], grad_fn=<AddBackward0>)
tensor([[74.6255]], grad_fn=<AddBackward0>)
tensor([[72.1919]], grad_fn=<AddBackward0>)
tensor([[78.0956]], grad_fn=<AddBackward0>)
tensor([[81.8577]], grad_fn=<AddBackward0>)
tensor([[74.3593]], grad_fn=<AddBackward0>)
tensor([[74.8424]], grad_fn=<Add

tensor([[70.8663]], grad_fn=<AddBackward0>)
tensor([[74.1374]], grad_fn=<AddBackward0>)
tensor([[74.1112]], grad_fn=<AddBackward0>)
tensor([[72.9112]], grad_fn=<AddBackward0>)
tensor([[74.3966]], grad_fn=<AddBackward0>)
tensor([[73.0808]], grad_fn=<AddBackward0>)
tensor([[72.8647]], grad_fn=<AddBackward0>)
tensor([[70.2969]], grad_fn=<AddBackward0>)
tensor([[74.9688]], grad_fn=<AddBackward0>)
tensor([[72.2770]], grad_fn=<AddBackward0>)
tensor([[73.3888]], grad_fn=<AddBackward0>)
tensor([[77.8520]], grad_fn=<AddBackward0>)
tensor([[80.9185]], grad_fn=<AddBackward0>)
tensor([[70.7434]], grad_fn=<AddBackward0>)
tensor([[75.0736]], grad_fn=<AddBackward0>)
tensor([[79.6015]], grad_fn=<AddBackward0>)
tensor([[67.9459]], grad_fn=<AddBackward0>)
tensor([[67.4036]], grad_fn=<AddBackward0>)
tensor([[74.4093]], grad_fn=<AddBackward0>)
tensor([[75.2383]], grad_fn=<AddBackward0>)
tensor([[73.5273]], grad_fn=<AddBackward0>)
tensor([[75.4069]], grad_fn=<AddBackward0>)
tensor([[74.1946]], grad_fn=<Add

In [24]:
g, y = ds_te[0]
y_hat = net(g).nodes['g'].data['y_hat'].flatten()
y = y.flatten()

NotImplementedError: 

In [51]:
g, y = ds_te[0]
y_hat = net.condition(g).mean.flatten()

In [52]:
import pinot

In [53]:
pinot.metrics._rmse(y, y_hat)

tensor(0.8571, grad_fn=<SqrtBackward>)

In [54]:
pinot.metrics._r2(y, y_hat)

tensor(-1263.7506, grad_fn=<RsubBackward1>)

In [55]:
y_hat

tensor([1.8962, 1.7389, 1.7109, 3.6542, 0.5547, 2.0893, 2.0951, 2.8599, 3.4595,
        3.3157, 2.6996, 3.2975, 2.6771, 2.3131, 0.6244, 2.6719, 3.5319, 3.2565,
        2.9515, 1.5560, 1.8059, 2.6634, 1.3564, 3.1694, 3.1021, 2.1757, 1.8495,
        2.7364, 0.6239, 2.8706, 1.2194, 2.9288, 1.8209, 2.6267, 0.9919, 2.4722,
        1.5585, 0.6461, 1.6152, 2.1739, 3.0723, 2.4409, 2.5752, 0.7603, 3.3591,
        2.6206, 2.4285, 3.1807, 0.4366, 2.5867, 1.0730, 2.5569, 3.2205, 0.3127,
        2.9035, 2.0861, 3.0770, 0.5480, 2.2614, 2.8232, 3.0437, 2.2974, 1.3055,
        1.9429, 2.7525, 2.9244, 2.1976, 0.9150, 1.2233, 1.7025, 2.2313, 1.2726,
        0.7632, 2.9920, 3.4580, 2.6353, 1.4292, 1.9558, 3.2197, 2.0388, 2.2036,
        0.7750, 2.3441, 0.0325, 1.3064, 3.0538, 1.7286, 3.3628, 3.1099, 2.2866,
        1.6544, 2.7808, 2.1229, 1.7275, 3.1565, 2.1263, 3.5095, 3.2875, 3.0388,
        2.3096, 2.7840, 2.8217, 2.7146, 2.3123, 0.7803, 2.3417, 3.1980, 2.9467,
        3.0488, 0.5518, 2.6724, 2.9796, 

In [45]:
y

tensor([[ 2.8000],
        [-0.3800],
        [ 1.9100],
        [ 3.4000],
        [-0.3800],
        [ 2.5500],
        [ 1.6400],
        [ 3.3000],
        [ 3.3800],
        [ 1.1300],
        [ 3.3700],
        [ 3.2700],
        [ 1.7400],
        [ 1.2000],
        [ 0.3600],
        [ 3.3700],
        [ 3.0000],
        [ 3.2700],
        [ 2.8800],
        [-0.5500],
        [ 1.2600],
        [ 3.5900],
        [ 2.0000],
        [ 3.0900],
        [ 3.0100],
        [ 3.1300],
        [ 3.6300],
        [ 1.1500],
        [ 2.3000],
        [ 2.4900],
        [ 0.9900],
        [ 3.3700],
        [ 2.0800],
        [ 2.5000],
        [ 0.8800],
        [ 3.1700],
        [ 1.2000],
        [ 2.3000],
        [ 1.1000],
        [ 1.5000],
        [ 3.8000],
        [ 2.8000],
        [ 2.8600],
        [-1.1700],
        [ 3.4500],
        [ 2.1700],
        [ 2.9000],
        [ 2.1800],
        [ 0.3000],
        [ 2.5500],
        [-0.3400],
        [ 4.1000],
        [ 3.